language: ruby
script: rspec spec -f d

install:
  - gem update bundler
  - bundle install

rvm:
  - ruby-head
  - jruby-head
  - jruby-19mode
  - 1.9
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - 3.0.0

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

env:
  global:
    - VERBOSE=true
    - TIMEOUT=1
    - BENCHMARK_QUANTITY=100000
    - STREAM_FILE_SIZE=68

branches:
  only:
    - master

notifications:
  email:
    - adamluzsi@gmail.com
