language: ruby
script: rspec spec -f d

install:
  - gem update bundler
  - bundle install

rvm:
  - ruby-head
  - jruby-head
  - 2.5
  - 2.6
  - 2.7
  - 3.0

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

env:
  global:
    - VERBOSE=true
    - TIMEOUT=1
    - BENCHMARK_QUANTITY=100000
    - STREAM_FILE_SIZE=68

notifications:
  email:
    - adamluzsi@gmail.com
